let nombreMedicamento = document.getElementById("nombremedicamento")
let presentacionMedicamento = document.getElementById("presentacionmedicamento")
let dosisMedicamento = document.getElementById("dosismedicamento")
let laboratorioMedicamento = document.getElementById("laboratorioMedicamento")
let caducidadMedicamento = document.getElementById("caducidadmedicamento")
let contraindicacionesMedicamento = document.getElementById("contraindicacionesmedicamento")